// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmH9Blgn4WbBpsKuB6BSKxpkCzrc3-f54',
    appId: '1:536062210625:web:b17278b055e48262d10cc0',
    messagingSenderId: '536062210625',
    projectId: 'um-qais',
    authDomain: 'um-qais.firebaseapp.com',
    storageBucket: 'um-qais.appspot.com',
    measurementId: 'G-LVW7G5N35P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKfMMcsug5nm-0eSlo0OQjaZoGNrWbmkc',
    appId: '1:536062210625:android:02d229130fb095a8d10cc0',
    messagingSenderId: '536062210625',
    projectId: 'um-qais',
    storageBucket: 'um-qais.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANQuM99IGKTtgk5L73h-dzE4HkLA1nOwU',
    appId: '1:536062210625:ios:6fe7ceccf1ee8529d10cc0',
    messagingSenderId: '536062210625',
    projectId: 'um-qais',
    storageBucket: 'um-qais.appspot.com',
    iosBundleId: 'com.example.umQais',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANQuM99IGKTtgk5L73h-dzE4HkLA1nOwU',
    appId: '1:536062210625:ios:c1295e7bdb11b46ad10cc0',
    messagingSenderId: '536062210625',
    projectId: 'um-qais',
    storageBucket: 'um-qais.appspot.com',
    iosBundleId: 'com.example.umQais.RunnerTests',
  );
}
